services:

  grpc-server:
    build:
      context: ./grpc-server
    ports:
      - "8080"  # เปิดเฉพาะภายใน ไม่ fix host port
    networks:
      - grpc-net

  grpc-client:
    build:
      context: ./grpc-client
    container_name: grpc-client
    depends_on:
      - grpc-server
    networks:
      - grpc-net
    command: ["java", "-jar", "/app.jar"]

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - grpc-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - grpc-net

networks:
  grpc-net:

volumes:
  grafana-data: